// <auto-generated />
namespace WebadmiClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UltimaMigracion1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UltimaMigracion1));
        
        string IMigrationMetadata.Id
        {
            get { return "202403092044167_UltimaMigracion1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
